# Generated by Django 5.0.6 on 2024-06-04 11:36

import django.db.models.deletion
import history4feed.app.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', history4feed.app.models.SlugField(max_length=1000, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=10240)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('earliest_item_pubdate', models.DateTimeField(null=True)),
                ('latest_item_pubdate', models.DateTimeField(null=True)),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('feed_type', models.CharField(choices=[('rss', 'Rss'), ('atom', 'Atom')], editable=False, max_length=12)),
                ('retrieve_full_text', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('run_datetime', models.DateTimeField(auto_now_add=True)),
                ('earliest_item_requested', models.DateTimeField()),
                ('latest_item_requested', models.DateTimeField()),
                ('info', models.CharField(max_length=10240)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.feed')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(blank=True, max_length=2097152)),
                ('link', models.URLField(max_length=1000)),
                ('pubdate', models.DateTimeField()),
                ('author', models.CharField(max_length=1000)),
                ('is_full_text', models.BooleanField(default=False)),
                ('content_type', models.CharField(default='plain/text', max_length=200)),
                ('categories', models.ManyToManyField(related_name='posts', to='app.category')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='app.feed')),
            ],
        ),
        migrations.CreateModel(
            name='FulltextJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('retrieved', 'Retrieved'), ('skipped', 'Skipped'), ('failed', 'Failed'), ('retrieving', 'Retrieving')], default='retrieving', max_length=15)),
                ('error_str', models.CharField(blank=True, max_length=1500, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fulltext_jobs', to='app.job')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.post')),
            ],
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('link', 'feed'), name='unique_link_by_field'),
        ),
    ]
