# Generated by Django 5.0.6 on 2024-07-15 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_feed_datetime_added_alter_feed_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.job'),
        ),
    ]
