# Generated by Django 5.0.6 on 2024-07-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_post_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='id',
            field=models.UUIDField(help_text='UUID of feed generated by history4feed', primary_key=True, serialize=False),
        ),
    ]
