# Generated by Django 5.0.6 on 2024-07-31 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_feed_retrieve_full_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulltextjob',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.post'),
        ),
    ]
