# Generated by Django 5.0.6 on 2024-08-01 09:17

from django.db import migrations, models
from history4feed.app.models import FulltextJob
from django.db.models import Subquery, OuterRef


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    FulltextJobModel : FulltextJob = apps.get_model('app', 'FulltextJob')
    FulltextJobModel.objects.filter(post__isnull=False).update(link=Subquery(FulltextJobModel.objects.filter(pk=OuterRef('pk')).values('post__link')))
    FulltextJobModel.objects.filter(post__isnull=True).update(link="https://example.com/blog-link")

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_feed_include_remote_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulltextjob',
            name='link',
            field=models.CharField(default='', max_length=1500),
            preserve_default=False,
        ),
        migrations.RunPython(forwards_func, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='fulltextjob',
            name='post',
            field=models.OneToOneField(null=True, on_delete=models.deletion.SET_NULL, to='app.post'),
        )
    ]

