# Generated by Django 5.0.6 on 2024-08-28 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_fulltextjob_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulltextjob',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
