# Generated by Django 5.0.6 on 2024-08-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_fulltextjob_post_alter_post_datetime_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(help_text='UUID of items generated by history4feed', primary_key=True, serialize=False),
        ),
    ]
