# Generated by Django 5.2.9 on 2026-04-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history4feed', '0010_increase_max_length_for_post_description'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(condition=models.Q(('deleted_manually', False)), fields=['pubdate'], name='h4f_pubdate_visible'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['id', 'deleted_manually'], name='h4f_deleted_manually_with_pkey'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(condition=models.Q(('deleted_manually', False)), fields=['datetime_added'], name='h4f_datetime_added'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(condition=models.Q(('deleted_manually', False)), fields=['datetime_updated'], name='h4f_datetime_updated'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(condition=models.Q(('deleted_manually', False)), fields=['title'], name='h4f_title_visible'),
        ),
    ]
