# Generated by Django 5.0.6 on 2024-09-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_post_job_alter_fulltextjob_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='profile_id',
            field=models.UUIDField(null=True),
        ),
    ]
