# Generated by Django 5.2.9 on 2026-06-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history4feed', '0011_post_h4f_pubdate_visible_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['feed_id', 'id'], name='h4f_feed_pk'),
        ),
        migrations.AlterField(
            model_name='job',
            name='completion_time',
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='run_datetime',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='time job was executed'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['feed_id', 'id'], name='h4f_job_feed_pk'),
        ),
    ]
