# Generated by Django 5.0.6 on 2024-09-26 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_job_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='profile_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
