# Generated by Django 5.0.8 on 2024-10-09 05:58

import history4feed.app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_job_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='url',
            field=models.URLField(help_text='\nThe URL of the RSS or ATOM feed\n\nNote this will be validated to ensure the feed is in the correct format.\n', max_length=1000, unique=True, validators=[history4feed.app.models.normalize_url]),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='categories of the post', related_name='posts', to='app.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(help_text='link to full article. found in the <item> element of feed output', max_length=1000, validators=[history4feed.app.models.normalize_url]),
        ),
    ]
