# Generated by Django 5.0.6 on 2024-10-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_feed_url_alter_post_categories_alter_post_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='include_remote_blogs',
        ),
        migrations.AddField(
            model_name='job',
            name='include_remote_blogs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='added_manually',
            field=models.BooleanField(default=False),
        ),
    ]
