# Generated by Django 5.0.6 on 2024-10-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_feed_include_remote_blogs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, help_text='author of the post', max_length=1000, null=True),
        ),
    ]
